import localFont from 'next/font/local';
import './globals.css';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export const pretendard = localFont({
  src: '../../public/font/PretendardVariable.woff2',
  variable: '--font-pretendard',
  display: 'swap',
});

export default function RootLayout({ children }) {
  return (
    <html lang="ko" className={pretendard.className}>
      <body className={`flex justify-center w-screen bg-dorong-primary-main`}>
        <main className="min-w-[500px] min-h-screen bgre bg-dorong-gray-1 text-center">
          {children}
        </main>
      </body>
    </html>
  );
}
